name: coinex-bot

networks:
  app:

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      app:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      app:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redis:/data
    networks:
      app:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    image: rabbitmq:3-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      app:

  taskiq-worker:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: taskiq-worker
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      bot:
        condition: service_started
    command: >
      taskiq worker core.taskiq.broker:broker --workers 1 -fsd --tasks-pattern "**/tasks"
    networks:
      app:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  taskiq-scheduler:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: taskiq-scheduler
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      bot:
        condition: service_started
    command: >
      taskiq scheduler core.taskiq.broker:scheduler -fsd --tasks-pattern "**/tasks"
    networks:
      app:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres:
  redis:
  rabbitmq-data:
